version: '{branch}-build{build}'
image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'

build_script:
  - sh: dotnet build -c Release

test_script:
  - sh: dotnet test -c Release --no-build

after_test:
  - sh: chmod +x pack.sh && ./pack.sh

artifacts:
  - path: '**\artifacts\nuget\*.nupkg'
    name: Nuget
  - path: '**\artifacts\myget\*.nupkg'
    name: Myget
  
deploy:
  - provider: NuGet
    api_key:
      secure: PtfAzDzYtEFjYKQmsfbJAXRrqlWDR2CesuEeupukTeyyD7O9bzMtRXHmBVYUu1sJ
    on:
      APPVEYOR_REPO_TAG: true
      
  - provider: NuGet
    server: https://www.myget.org/F/prometheus-client-net/api/v2/package
    api_key:
      secure: DvXZQgy0wcMjR87Zt1qBB9YaDmEiAAiylRxVFfnvkYmfD+oYUetgCi1B036DJZGF
    symbol_server: https://www.myget.org/F/prometheus-client-net/symbols/api/v2/package
    artifact: MyGet
    on:
      branch: master
      APPVEYOR_REPO_TAG: false
